# ------------------------------------------------
# 请确保 theme_config 紧贴左边行号，不要留空隙
# ------------------------------------------------
theme_config:
  background: /bg.png
  avatar:
    img: https://unpkg.com/hexo-theme-butterfly/source/img/avatar.png
    effect: true
  notice:
    enable: true
    content: "配置成功"
