# 1. 背景图 (直接用网图，排除本地路径问题)
background: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/402px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg

# 2. 头像
avatar:
  img: https://unpkg.com/hexo-theme-butterfly/source/img/avatar.png
  effect: true

# 3. 公告
notice:
  enable: true
  content: "如果在看蒙娜丽莎，说明配置成功了"
